name: Distillation Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  distillation-tests:
    name: Distillation Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Chrome Fleet
        uses: ./.github/actions/run-chromefleet
        timeout-minutes: 5

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Run the distillation tests
        run: uv run pytest -m "distill" -s -p no:xdist
        env:
          CHROMEFLEET_URL: http://localhost:8300
          ACME_EMAIL: joe@example.com
          ACME_PASSWORD: trustno1
          ACME_OTP: 123456
